### ISSUE TITLE
Create a flatpak manifest for an Endless Key app

### ISSUE THREAD

**Issue by dbnicholson** [endlessm/endless-key-flatpak#4]
The Endless Key app should be similar to the Kolibri app, except it will need to build kolibri-gnome with several different options, and include kolibri-explore-plugin. In particular, it will need to specify a different app ID and app name, and a default list of plugins to enable and disable. Ideally, we would like to apply some light customization with build options or configuration files, rather than maintaining a fork.

Prepare to publish the resulting app on Flathub as org.endlessos.EndlessKey.

**Comment by dylanmccall** [comment]
I created https://github.com/endlessm/endless-key-flatpak/issues/7 to split out the handwavey "we need to be able to build kolibri-gnome to look like Endless Key" part :)

**Comment by dbnicholson** [comment]
My only nitpick is that I think the app ID should be `org.endlessos.Key` to match the Android app. I don't think the "Endless" in the "Endless Key" friendly name needs to be separately reflected in the app ID as it's already implied by `org.endlessos`.

**Comment by dbnicholson** [comment]
This was actually fixed in #7 for the [devel flatpak](https://github.com/endlessm/endless-key-flatpak/blob/main/build-aux/flatpak/org.endlessos.Key.Devel.json). The flathub manifest will be essentially a duplicate of that, but it will be handled in #5.

One thing that would be nice is converting the devel manifest to YAML since that's what they'll want at Flathub. Not necessary, though.

**Comment by dylanmccall** [comment]
> This was actually fixed in #7 for the [devel flatpak](https://github.com/endlessm/endless-key-flatpak/blob/main/build-aux/flatpak/org.endlessos.Key.Devel.json). The flathub manifest will be essentially a duplicate of that, but it will be handled in #5.
> 
> One thing that would be nice is converting the devel manifest to YAML since that's what they'll want at Flathub. Not necessary, though.

The reason why the devel manifest is a JSON is because Builder doesn't want to deal with YAMLs at the moment: https://gitlab.gnome.org/GNOME/gnome-builder/-/merge_requests/583.

The production manifest is a YAML file and we should absolutely be using that for the Endless Key flatpak as well: https://github.com/flathub/org.learningequality.Kolibri.

This is a bit annoying, but for the most part it's _fine_: most of the modules are in separate files so those can just be copied as-is, and the production manifest has some different metadata bits (and some extra modules) anyway.

**Comment by starnight** [comment]
Yap!  Have the YAML in the PR [Add org.endlessos.Key](https://github.com/flathub/flathub/pull/4481) to Flathub!
