### ISSUE TITLE
Endless curated channels "Best of the Web" title is showing code

### ISSUE THREAD

**Issue by jofilizola** [endlessm/endless-key-flatpak#77]
The text "Best of the Web" should be bold

![Image](https://github.com/endlessm/endless-key-flatpak/assets/51095367/39ce54d9-2c76-483c-91a5-7eb1a8bc5f00)

**Comment by dbnicholson** [comment]
I looked at this in chrome and the entire Best of the Web is included in the surrounding `<div>` as text. I.e., there are no child nodes as would be required to actually render `<strong>`.

As far as I can tell, this is because [`formatMessage`](https://formatjs.io/docs/intl#formatmessage) is always returning a string in vue-intl. In react-intl, there's an override to return an array of `React.ReactNode`. I think something similar would be needed in vue-intl so that Vue didn't just see a string being supplied to the parent node.

I believe the options are:

1. Untranslate it.
2. Break the `<strong>Best of the Web</strong> curated by ` message into two translations.
3. Fix vue-intl so it can provide Vue nodes instead of just a string.
4. Some local hack that splits up the returned string into nodes.

@manuq @pwithnall any suggestions? I think in the very short term I'm just going to go with 1.

**Comment by dbnicholson** [comment]
Oh, I just noticed the use of `v-html` in 674ceed10a6d06d54649f6c6a5554b6c655f2538. Probably we can do something similar.

**Comment by vanessa-chang** [comment]
Verified Passed with v0.7 dev package
